CREATE DATABASE DevLink_db;

CREATE TABLE Users (
userID INT PRIMARY KEY,
username VARCHAR(50) UNIQUE NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(100) NOT NULL,
userType VARCHAR(20) NOT NULL
);

CREATE TABLE Admin (
userID INT PRIMARY KEY,
permissions TEXT NOT NULL,
FOREIGN KEY (userID) REFERENCES Users(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Member (
userID INT PRIMARY KEY,
interest VARCHAR(100),
verified BOOLEAN DEFAULT FALSE,
FOREIGN KEY (userID) REFERENCES Users(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);


CREATE TABLE UserFollow (
userID INT,
followerID INT ,
PRIMARY KEY (userID, followerID),
FOREIGN KEY (userID) REFERENCES Users(userID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (followerID) REFERENCES Users(userID)
ON DELETE CASCADE
ON UPDATE CASCADE
);